version: "3"

networks:
  rethink-net:
    driver: overlay

services:
  testapp:
    image: zen12/rethinkdb-cluster:testapp
    networks:
      - rethink-net
    environment:
      - "dbservers=rethinkdb1;rethinkdb2;rethinkdb3;rethinkdb4;rethinkdb5"

  rethinkdb1:
    image: zen12/rethinkdb-cluster
    environment:
      - "JOIN=rethinkdb1,rethinkdb2,rethinkdb3,rethinkdb4,rethinkdb5"
      - "RETHINKARGS=--server-tag rethinkdb1 --server-name rethinkdb1"
    hostname: rethinkdb1
    volumes:
      - /datavol/rethinkdb/db1:/data
    networks:
      - rethink-net
    ports:
      - 8081:8080

  rethinkdb2:
    image: zen12/rethinkdb-cluster
    environment:
      - "JOIN=rethinkdb1,rethinkdb2,rethinkdb3,rethinkdb4,rethinkdb5"
      - "RETHINKARGS=--server-tag rethinkdb2 --server-name rethinkdb2"
    hostname: rethinkdb2
    volumes:
      - /datavol/rethinkdb/db2:/data
    networks:
      - rethink-net
    ports:
      - 8082:8080

  rethinkdb3:
    image: zen12/rethinkdb-cluster
    environment:
      - "JOIN=rethinkdb1,rethinkdb2,rethinkdb3,rethinkdb4,rethinkdb5"
      - "RETHINKARGS=--server-tag rethinkdb3 --server-name rethinkdb3"
    hostname: rethinkdb3
    volumes:
      - /datavol/rethinkdb/db3:/data
    networks:
      - rethink-net
    ports:
      - 8083:8080

  rethinkdb4:
    image: zen12/rethinkdb-cluster
    environment:
      - "JOIN=rethinkdb1,rethinkdb2,rethinkdb3,rethinkdb4,rethinkdb5"
      - "RETHINKARGS=--server-tag rethinkdb4 --server-name rethinkdb4"
    hostname: rethinkdb4
    volumes:
      - /datavol/rethinkdb/db4:/data
    networks:
      - rethink-net
    ports:
      - 8084:8080

  rethinkdb5:
    image: zen12/rethinkdb-cluster
    environment:
      - "JOIN=rethinkdb1,rethinkdb2,rethinkdb3,rethinkdb4,rethinkdb5"
      - "RETHINKARGS=--server-tag rethinkdb5 --server-name rethinkdb5"
    hostname: rethinkdb5
    volumes:
      - /datavol/rethinkdb/db5:/data
    networks:
      - rethink-net
    ports:
      - 8085:8080
