version: "3"

networks:
  rethink-net:
    driver: overlay

services:
  testapp:
    image: zen12/rethinkdb-cluster:testapp
    networks:
      - rethink-net
    environment:
      - "dbservers=rethinkdb1;rethinkdb2;rethinkdb3;rethinkdb4;rethinkdb5"

  rethinkdb1:
    image: zen12/rethinkdb-cluster
    environment:
      - "DBCLUSTERHOSTS=rethinkdb2;rethinkdb3;rethinkdb4;rethinkdb5"
      - "RETHINKARGS=--server-tag primary --server-name rethinkdb1 --bind all"
    hostname: rethinkdb1
    volumes:
      - /datavol/rethinkdb/db1:/data
    networks:
      - rethink-net
    ports:
      - 29015:29015
      - 28015:28015
      - 8081:8080

  rethinkdb2:
    image: zen12/rethinkdb-cluster
    environment:
      - "DBCLUSTERHOSTS=rethinkdb1;rethinkdb3;rethinkdb4;rethinkdb5"
      - "RETHINKARGS=--server-tag primary --server-name rethinkdb2 --bind all"
    hostname: rethinkdb2
    volumes:
      - /datavol/rethinkdb/db2:/data
    networks:
      - rethink-net
    ports:
      - 29016:29015
      - 28016:28015
      - 8082:8080

  rethinkdb3:
    image: zen12/rethinkdb-cluster
    environment:
      - "DBCLUSTERHOSTS=rethinkdb1;rethinkdb2;rethinkdb4;rethinkdb5"
      - "RETHINKARGS=--server-tag primary --server-name rethinkdb3 --bind all"
    hostname: rethinkdb3
    volumes:
      - /datavol/rethinkdb/db3:/data
    networks:
      - rethink-net
    ports:
      - 29017:29015
      - 28017:28015
      - 8083:8080

  rethinkdb4:
    image: zen12/rethinkdb-cluster
    environment:
      - "DBCLUSTERHOSTS=rethinkdb1;rethinkdb2;rethinkdb3;rethinkdb5"
      - "RETHINKARGS=--server-tag primary --server-name rethinkdb4 --bind all"
    hostname: rethinkdb4
    volumes:
      - /datavol/rethinkdb/db4:/data
    networks:
      - rethink-net
    ports:
      - 29018:29015
      - 28018:28015
      - 8084:8080

  rethinkdb5:
    image: zen12/rethinkdb-cluster
    environment:
      - "DBCLUSTERHOSTS=rethinkdb1;rethinkdb2;rethinkdb3;rethinkdb4"
      - "RETHINKARGS=--server-tag primary --server-name rethinkdb5 --bind all"
    hostname: rethinkdb5
    volumes:
      - /datavol/rethinkdb/db5:/data
    networks:
      - rethink-net
    ports:
      - 29019:29015
      - 28019:28015
      - 8085:8080
